name: b1gtv
description: B1G - IPTV player for Android TV and Fire TV (live TV, movies and series).
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  qr_flutter: ^4.1.0
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_android_video: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
